### ISSUE TITLE
glfw3 will Change process woking dir to the application bundle's resources directory in macos

### ISSUE THREAD

**Issue by xiconxi** [pyglfw/pyglfw#4]
just as the title, it's possible to modify pyglfw.pyglfw.init() to
```
def init():
    import os
    with os.getcwd() as cwd, bool(api.glfwInit()) as ret : 
        os.chdir(cwd)
        return ret
```

**Comment by xiconxi** [comment]
for more details:
https://github.com/glfw/glfw/blob/a337c568486025d22443535b7c047a563bc34373/src/cocoa_init.m
Line: 35

**Comment by RomanValov** [comment]
As per docs ( https://www.glfw.org/docs/latest/group__init.html ), GLFW provides new library call `glfwInitHint` with possibility to alter `glfwInit` behavior since GLFW 3.3. I would rather merge a pull-request with support of `glfwInitHint` and appropriate constants added.
