### ISSUE TITLE
key callback receiving incorrectly typed args

### ISSUE THREAD

**Issue by sn1572** [pyglfw/pyglfw#8]
Howdy! First off, love the library and thank you for porting it.

The signature of `key_callback` (per [the docs](https://www.glfw.org/docs/3.3/input_guide.html#input_key)) is supposed to be a pointer to a glfw window and four ints. I am defining my callback like so (github eats my whitespace):

@CFUNCTYPE(None, c_void_p, c_int, c_int, c_int, c_int)
def keyboard_callback(window, key, scancode, action, mods):
print(type(window))
_active_cam.key_callback(window, key, scancode, action, mods)

and the output I receive is:

<class 'int'>
[...]
ctypes.ArgumentError: argument 1: TypeError: expected LP__GLFWwindow instance instead of int

It seems that somewhere in the plumbing the integer value of the window pointer address is being passed instead of the window pointer itself. This issue does not seem to be occurring with the mouse or scroll callbacks.

**Comment by RomanValov** [comment]
Hi. Thanks for the feedback. Have you checked examples directory?
In particular there is an example of key callback could be found at `raw_api.py` (libapi version).
Additionally please check `onevent.py` (pyglfw version).

**Comment by sn1572** [comment]
Ah, thank you for pointing those out! Seems I was doing it the hard way.
